name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "$LIGHTSAIL_KEY" > lightsail_key.pem
          chmod 600 lightsail_key.pem

      - name: Deploy to Lightsail
        run: |
          ssh -o StrictHostKeyChecking=no -6 -i lightsail_key.pem $LIGHTSAIL_USER@$LIGHTSAIL_HOST "
            cd /home/ubuntu/Flood-Prediction-Backend &&
            git pull &&
            npm install &&
            pm2 restart all
          "
